export const AUTH_SERVICE = 'AUTH_SERVICE';
export const AUCTION_MANAGEMENT_SERVICE = 'AUCTION_MANAGEMENT_SERVICE';
export const BID_SERVICE = 'BID_SERVICE';
export const PAYMENT_SERVICE = 'PAYMENT_SERVICE';
export const INVENTORY_SERVICE = 'INVENTORY_SERVICE';
export const API_GATEWAY_SERVICE = 'API_GATEWAY_SERVICE';
